//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AccountBook
    {
        public System.Guid Id { get; set; }
        [Display(Name = "類別", Description = "類別")]
        public int Categoryyy { get; set; }
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        [Display(Name = "金額", Description = "交易金額")]
        public int Amounttt { get; set; }
        [Display(Name = "日期", Description = "交易日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime Dateee { get; set; }
        [Display(Name = "備註", Description = "交易備註")]
        public string Remarkkk { get; set; }
    }
}
